name: CI

on:
  push:
    branches:
      - '**'
env:
  BUILDKIT_IMAGE: jkaninda/portfolio   
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14.x'
    - name: Install yarn dependencies
      run: yarn install
    - name: Run build task
      run: yarn run build --if-present
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          EXCLUDE: "/dist/, /node_modules/"
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Set environment for branch
        run: |
          set -x
          if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
            echo "TAG_NAME=latest" >> "$GITHUB_ENV"
            echo "runs-on: main branch"
          else
            echo "TAG_NAME=${{ github.head_ref || github.ref_name }}" >> "$GITHUB_ENV"
            echo "runs-on: ${{ github.head_ref || github.ref_name }} branch"
          fi
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: "${{env.BUILDKIT_IMAGE}}:${{env.TAG_NAME}}"