jobs:
  build:
    docker:
    # Primary container image where all steps run.
     - image: cimg/base:current

    steps:
      # command will execute in an Ubuntu-based container
      - run: docker build -t docker/Dockerfile porfolio:latest .
      - run: docker image ls
