name: CI

on:
  push:
    branches:
      - '**'
env:
  BUILDKIT_IMAGE: jkaninda/portfolio
  TAG_NAME: ""   
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Set environment for branch
        run: |
          set -x
          echo "TAG_NAME=$(date +%Y%m%d_%H%M%S)" >> "$GITHUB_ENV"
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: "./docker/Dockerfile"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
           "${{env.BUILDKIT_IMAGE}}:${{env.TAG_NAME}}"
           "${{env.BUILDKIT_IMAGE}}:latest"